apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: nginx-ns
spec:
  hard:
    pods: "5"  # Maximum number of Pods in the Namespace
    requests.cpu: "3000m"       # Minimum CPU request [1/2 Core] in the Namespace
    requests.memory: "5Gi"  # Minimum Memory request in the Namespace
    limits.cpu: "4000m"      # Maximum CPU limit [1.5 Core] in the Namespace
    limits.memory: "6Gi" # Maximum Memory limit in the Namespace