apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: service
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  # Read-only access to pods
  verbs: ["get", "list", "watch"]