apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  clusterIP: None   # Headless Service --->  Allow stable DNS resolution between pods
  selector:
    app: mysql
  ports:
    - port: 3306