apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  annotations:
    kubernetes.io/change-cause: "Nginx"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: mycontainer
        image: nginx
        ports:
        - name: myport
          containerPort: 80
